name: Build DEB package

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - Preview
      - Lenovo-LOQ

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            fakeroot \
            dpkg-dev


      - name: Build DEB package
        run: |
          chmod +x packaging/deb/build_deb.sh
          packaging/deb/build_deb.sh


      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-config
          path: |
            *.deb
            dist/*.deb
            packaging/deb/*.deb
